language: scala
jdk: oraclejdk8
scala:
    - 2.12.7
script:
    - "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt
notifications:
    email: false
